---
# Experiment Arguments
experiment_name: outlier_exposure_mura_beta_0.5
iid_name: mura
mode: outlier_exposure
ood_names: 
  - skeletal-age
  - mimic-cxr
  - retina
num_models: 5

# Hyper Parameters
num_epochs: 20
batch_size: 32
beta: 0.5

# Training params
lr: 0.0001
early_stop: 5
eval_start: 10
num_workers: 8
