---
# Experiment Arguments
experiment_name: outlier_exposure_retina_beta_0.1
iid_name: retina
mode: outlier_exposure
ood_names: 
  - skeletal-age
  - mura
  - mimic-cxr
num_models: 5

# Hyper Parameters
num_epochs: 20
batch_size: 32
beta: 0.1

# Training params
lr: 0.0001
early_stop: 5
eval_start: 10
num_workers: 8
